language: php

php:
  - 5.5
  - 5.6

before_script:
  - yes | pecl install -f apcu-4.0.6
  - echo "apc.enabled=1" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
  - echo "apc.enable_cli=1" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
  - wget http://getcomposer.org/composer.phar
  - php composer.phar install --dev

script:
  - vendor/bin/atoum
  - vendir/bin/coke
