language: php

php:
  - 5.4
  - 5.5

before_script:
  - pecl install -f apcu
  - echo "extension=apcu.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
  - echo "apc.enabled=1" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
  - echo "apc.enable_cli=1" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
  - wget http://getcomposer.org/composer.phar
  - php composer.phar install --dev

script:
  - vendor/bin/atoum